### ISSUE TITLE
If ScreenCast is installed on the MagicMirror, the integration doesn't work.

### ISSUE THREAD

**Issue by fribse** [sindrebroch/ha-magicmirror#2] opened 2022-02-13 19:23 UTC
## Version of the custom_component

1.1.4
## Configuration

![billede](https://user-images.githubusercontent.com/13660621/153771104-6ac43759-9467-4c7f-ac0a-9366998c1e56.png)

```yaml
                {
                        module: "MMM-Remote-Control",
                        config: {
                                apiKey: 'b9911c8282f943faac207140f4e8ea0a',
                                showModuleApiMenu: true,
                                pm2ProcessName: 'MagicMirror',
//                              customCommand: {
//                                      playGhostvideo: '/home/pi/randomfile.sh'
//                                      }
                                },
                },/*
                {
                        module: "MMM-Screencast",
                        position: "'bottom_right", // This position is for a hidden <div /> and not the screencast window
                        config: {
                                position: "bottomRight",
                                castName: "Spejl",
                                height: 300,
                                width: 500,
                        }
                },*/

```

As soon as I uncomment the Screencast module, the integration goes away.

## Describe the bug
If I activate the Screencast module in MagicMirror, the integration doesn't work.
I can go to 'IP:8080/remote.html' with a browser and turn the monitor on/off etc.

## Debug log

```text

Denne fejl stammer fra en brugerdefineret integration.

Logger: custom_components.magicmirror
Source: helpers/update_coordinator.py:219
Integration: Magic Mirror (documentation, issues)
First occurred: 18.39.45 (3 occurrences)
Last logged: 19.54.28

Error fetching magicmirror data: Cannot connect to host 10.11.12.17:8080 ssl:default [Connect call failed ('10.11.12.17', 8080)]

```

**Comment by sindrebroch** [comment] 2022-02-14 09:41
Weird, will take a look at it at some point. Haven't used MMM-Screencast myself, so no experience there.

Thank you for reporting the issue.

**Comment by fribse** [comment] 2022-02-14 20:59
You are most welcome, it's really odd, as far as I know the screencast opens some completely different ports, so I have no idea why it conflicts with it.

**Comment by sindrebroch** [comment] 2022-02-16 15:05
Weird. I tried adding MMM-Screencast and everything seems to work fine here. 

Not 100% sure that the screencast-module works, as I have my MagicMirror on a closed-down VLAN, so I can't really cast to it easily. But the logs in the browser says 
```
Starting module: MMM-Screencast
All modules started!
```
so it should be running.

Are there any errors in the browser? If you go to `IP:8080` and dev-tools -> console.

If not my next though would be trying to call the API yourself with a tool like Postman or similar. Is that something you are familiar with?

**Comment by fribse** [comment] 2022-02-16 18:14
This list might be better, without ScreenCast:

```
pi@bathmirror:~ $ netstat -lntup
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 10.11.12.17:8080        0.0.0.0:*               LISTEN      3385/electron.js
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      -
udp        0      0 0.0.0.0:68              0.0.0.0:*                           -
udp        0      0 0.0.0.0:51298           0.0.0.0:*                           -
udp   136256      0 0.0.0.0:5353            0.0.0.0:*                           -
```

With screencast:

```
pi@bathmirror:~ $ netstat -lntup
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 10.11.12.17:8080        0.0.0.0:*               LISTEN      3771/electron.js
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:8569            0.0.0.0:*               LISTEN      3771/electron.js
udp        0      0 0.0.0.0:68              0.0.0.0:*                           -
udp        0      0 0.0.0.0:51298           0.0.0.0:*                           -
udp        0      0 10.11.12.17:50887       0.0.0.0:*                           3771/electron.js
udp   143552      0 0.0.0.0:5353            0.0.0.0:*                           -
udp        0      0 0.0.0.0:1900            0.0.0.0:*                           3771/electron.js

```

**Comment by sindrebroch** [comment] 2022-02-17 08:25
Hmm not sure what that error is. Would have to dig into the magicmirror-code for that i guess. Doesn't seem to be any blocking ports.

If you can try sending a GET-request to:
`http://10.11.12.17:8080/api/monitor/status` 
with an added Header:
`Authorization: Bearer <MMM-Remote-Control API-key>`

Then we can at least know if the issue is in this integration or not.

**Comment by fribse** [comment] 2022-02-17 13:36
I'll try after work :-)

**Comment by sindrebroch** [comment] 2022-02-18 08:02
Seems like one of the requests are working at least... 

Good idea, I'll try it out later. 

Really weird this issue.

**Comment by sindrebroch** [comment] 2022-02-18 17:21
I tried your config and was still not able to recreate the issue. Not sure what more to suggest here. Kind of difficult to help when I'm not able to reproduce it...

These are the endpoints that are called, you can try all of them to check if any of them fails.
**To be able to set up:**
/api/test

**To fetch sensor-data:**
/api/mmUpdateAvailable
/api/monitor/status
/api/brightness

**Comment by sindrebroch** [comment] 2022-02-18 17:22
You could try turning on debug-logging from the README, and see if you get any more logs.

**Comment by fribse** [comment] 2022-02-20 19:56
Hi @sindrebroch 
What readme about the debug-logging ?

Without ScreenCast
![billede](https://user-images.githubusercontent.com/13660621/154861616-dfee38b5-ec41-4147-9f9e-52beb352a961.png)
/api/test:
`{"success":true}`
/api/mmUpdateAvailable
`{"success":true,"query":{"data":"mmUpdateAvailable"},"result":false}`
/api/monitor/status
`{"success":true,"monitor":"off"}`
/api/brightness
`{"success":true,"query":{"data":"brightness"},"result":100}`

With ScreenCast
![billede](https://user-images.githubusercontent.com/13660621/154861557-4f85cd66-5b4f-4499-8aae-b3614202de00.png)
/api/test:
`"success":false,"status":"error","reason":"unknown","info":"Not initialized, have you opened or refreshed your browser since the last time you started MagicMirror?"}`
/api/mmUpdateAvailable
`{"success":true,"query":{"data":"mmUpdateAvailable"},"result":false}`
/api/monitor/status
`{"success":true,"monitor":"on"}`
/api/brightness
`{"success":false,"status":"error","reason":"unknown","info":"Not initialized, have you opened or refreshed your browser since the last time you started MagicMirror?"}`

Hmmm? So both the module scheduler and the remote-control is somehow affected.
I've done a reinstall of MagicMirror, so the only thing left is the Raspberry OS I guess.
What version are you running?
Mine says
```
# cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

**Comment by sindrebroch** [comment] 2022-02-21 07:39
I'm running the same version as you. Are you running the latest version of MagicMirror as well? 

Sorry, I hadn't added the debug-section to this repository. Now it's there, but I think we have all we need from you requests. Two of the calls fails with error-status. Pretty sure this needs to be handled in MMM-Remote-Control or MMM-Screencast. 

I'll look into handling errors better, but I don't think your situation can be completely resolved by error handling when the underlying issue is somewhere else.

**Comment by fribse** [comment] 2022-02-21 14:14
I've made a new SD card, and I'm going to attempt a redo of the Magic Mirror installation. I've installed it with sdetwell's script, did you do the same?

**Comment by sindrebroch** [comment] 2022-02-21 14:42
To be honest I don't remember, but I think I did a manual install.

**Comment by fribse** [comment] 2022-02-25 15:30
Ok, so I did a complete reinstall, new Raspbian Buster, fully updated, both tried manual and automatic update.
When I install screencast I see this message at some point

```
0|MagicMirror  | [25.02.2022 16:24.54.686] [ERROR]
0|MagicMirror  | Whoops! There was an uncaught exception...
0|MagicMirror  | [25.02.2022 16:24.54.705] [ERROR]
0|MagicMirror  | Error [ERR_SERVER_ALREADY_LISTEN]: Listen method has been called more than once without closing.
0|MagicMirror  |     at new NodeError (node:internal/errors:371:5)
0|MagicMirror  |     at Server.listen (node:net:1405:11)
0|MagicMirror  |     at DialServer.start (/home/pi/MagicMirror/modules/MMM-Screencast/DialServer.js:123:17)
0|MagicMirror  |     at Class.socketNotificationReceived (/home/pi/MagicMirror/modules/MMM-Screencast/node_helper.js:22:21)
0|MagicMirror  |     at Socket.<anonymous> (/home/pi/MagicMirror/js/node_helper.js:109:11)
0|MagicMirror  |     at Socket.emit (node:events:394:28)
0|MagicMirror  |     at Socket.emitUntyped (/home/pi/MagicMirror/node_modules/socket.io/dist/typed-events.js:69:22)
0|MagicMirror  |     at /home/pi/MagicMirror/node_modules/socket.io/dist/socket.js:466:39
0|MagicMirror  |     at processTicksAndRejections (node:internal/process/task_queues:78:11) {
0|MagicMirror  |   code: 'ERR_SERVER_ALREADY_LISTEN'
0|MagicMirror  | }
0|MagicMirror  | [25.02.2022 16:24.54.712] [ERROR] MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
0|MagicMirror  | [25.02.2022 16:24.54.716] [ERROR] If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
```

And as soon as it is installed, the integration fails.

I don't understand that you can't reproduce it.

My config so far:

```
let config = {
	address: "10.11.12.17", 	// Address to listen on, can be:
	port: 8080,
	basePath: "/", 	// The URL path where MagicMirror is hosted. If you are using a Reverse proxy
	ipWhitelist: ["127.0.0.1", "10.11.12.0/24"], 	// Set [] to allow all IP addresses
	useHttps: false, 		// Support HTTPS or not, default "false" will use HTTP
	httpsPrivateKey: "", 	// HTTPS private key path, only require when useHttps is true
	httpsCertificate: "", 	// HTTPS Certificate path, only require when useHttps is true

	language: "da",
	locale: "da-DK",
	logLevel: ["INFO", "LOG", "WARN", "ERROR"], // Add "DEBUG" for even more logging
	timeFormat: 24,
	units: "metric",

	modules: [
		{
			module: "alert",
		},
		{
			module: "updatenotification",
			position: "top_bar"
		},
		{
			module: "clock",
			position: "top_left"
		},
		{
			module: "calendar",
			header: "Kalenderdage",
			position: "top_left",
			classes: "day_schedule small",
			config: {
				maximumEntries: 6,
				fetchInterval: 12000000 ,
				calendars: [
					{
						symbol: "calendar-check",
						url: "webcal://p01-calendarws.icloud.com/ca/subscribe/1/IsLh6fUURb4n_nA6vhWYUmlEe98rz2BN8BhioUPzrC2HVohwJIUCbGuGeTwczZWvXjTqU7vicBATXHojb1p5fn8ub3RCBUwKfHm3jXJDzFE"
					}
				]
			}
		},
		{
			module: "compliments",
			position: "lower_third",
			classes: "complimenttime bold xlarge bright",
			config: {
				remoteFile: "https://gist.githubusercontent.com/fribse/61731144a72f75e20b83b5388981ad07/raw/f58813dec5c7bd4caf0b629fb76742c026129117/compliments.json",
				updateInterval: 120000,
				morningStartTime: 05,
				morningEndTime: 10,
				afternoonStartTime: 15,
				afternoonEndTime: 18,
				}
		},
		{
			module: "weather",
			position: "top_right",
			classes: "day_schedule",
			config: {
				weatherProvider: "openweathermap",
				type: "current",
				units: "metric",
				timeFormat: 24,
				decimalSymbol: ",",
				initialLoadDelay: 0,
				onlyTemp: false,
				locationID: 2621215,
				apiKey: "xxx"
			}
		},
		{
			module: "weather",
			position: "top_right",
			classes: "day_schedule",
			config: {
				weatherProvider: "openweathermap",
				type: "forecast",
				units: "metric",
				timeFormat: 24,
				decimalSymbol: ",",
				initialLoadDelay: 0,
				onlyTemp: true,
				maxNumberOfDays: 7,
				colored: true,
				appendLocationNameToHeader: false,
				locationID: 2621215,
				apiKey: "xxx"
			}
		},
		{
			module: "newsfeed",
			position: "bottom_bar",
			classes: "day_schedule",
			config: {
				feeds: [
					{
						title: "Ekstra Bladet",
						url: "https://ekstrabladet.dk/rssfeed/all/"
					},
					{
						title: "DR nyheder",
						url: "https://www.dr.dk/nyheder/service/feeds/allenyheder"
					},
					{
						title: "BT",
						url: "https://www.bt.dk/bt/seneste/rss"
					},
					{
						title: "Berlingske.dk",
						url: "https://www.berlingske.dk/content/3/rss"
					},
					{
						title: "TV2 Ã˜st",
						url: "https://www.tv2east.dk/rss"
					}
				],
				updateInterval: 30000,
				showSourceTitle: true,
				showPublishDate: true,
				broadcastNewsFeeds: true,
				broadcastNewsUpdates: true
			}
		},
		{
			module: "MMM-Remote-Control",
			config: {
				apiKey: 'xxx',
				showModuleApiMenu: true,
				pm2ProcessName: 'MagicMirror',
				},
		},
		{
			module: "MMM-Screencast",
			position: "'bottom_right", // This position is for a hidden <div /> and not the screencast window
			config: {
				position: "bottomRight",
				port: 8569,
				castName: "Spejl",
				height: 300,
				width: 500,
			}
		},
	]
};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}

```

**Comment by sindrebroch** [comment] 2022-02-26 12:29
Weird. The error "[ERR_SERVER_ALREADY_LISTEN]: Listen method has been called more than once without closing.
" suggests that screencasts might be listening on some of the same ports I guess, but the response from the API calls are originating from the MMM-Remote-Control API. 

In the Remote-Control API, as the error suggests the problem is the class not being initialized. Reboots doesn't help either? Or maybe a browser refresh if that is possible?
```
    checkInititialized: function(res) {
        if (!this.initialized) {
            this.sendResponse(res, "Not initialized, have you opened or refreshed your browser since the last time you started MagicMirror?");
            return false;
        }
        return true;
    }
```

I don't really know what more I can bring to this issue, as the issue seems to be related to one or both of the other integrations.

**Comment by fribse** [comment] 2022-02-26 13:16
My problem is that you can't reproduce it, that part I can't get my head around, I can't figure out what I've done different than you.
I've made a new image with raspbian buster in 'normal' edition (ie. not lite or full), gotten it fully updated, and then installed MagicMirror, what on earth is wrong? You are on  2.18 with node.js fully updated, right?

**Comment by sindrebroch** [comment] 2022-03-04 10:48
Yeah it's weird indeed. Raspbian buster and 2.18 yes.

Seems I'm on node v14.19.0, so you could try changing that. I'll see if I get the time to update node at some point as well.

**Comment by sindrebroch** [comment] 2022-03-04 13:04
I tried upgrading to node v17.6.0, and the API still seems to work for me. 

I use pm2 to run mm as a process, and checked my pm2 logs for the first time. Not sure if these were present before, but I see a few errors now at least:

```
0|mm  | Fontconfig warning: ignoring UTF-8: not a valid region tag
0|mm  | [04.03.2022 13:59.00.661] [LOG]   
0|mm  | Launching application.
0|mm  | [04.03.2022 13:59.01.366] [ERROR] 
0|mm  | MODULE LIST ERROR: modules.json updating fail:EACCES: permission denied, open '/home/pi/MagicMirror/modules/MMM-Remote
-Control/modules.json'
0|mm  | [04.03.2022 13:59.01.368] [ERROR] ERROR_UPDATING
0|mm  | [1925:0304/135903.325370:ERROR:gpu_process_host.cc(968)] GPU process exited unexpectedly: exit_code=139
0|mm  | [1925:0304/135904.639423:ERROR:gpu_process_host.cc(968)] GPU process exited unexpectedly: exit_code=139
0|mm  | [1925:0304/135905.760081:ERROR:gpu_process_host.cc(968)] GPU process exited unexpectedly: exit_code=139
0|mm  | [2080:0304/135906.052026:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-
process.
``` 
```
0|mm  | [04.03.2022 13:59.15.929] [ERROR] 
0|mm  | Whoops! There was an uncaught exception...
0|mm  | [04.03.2022 13:59.15.969] [ERROR] 
0|mm  | Error [ERR_SERVER_ALREADY_LISTEN]: Listen method has been called more than once without closing.
0|mm  |     at new NodeError (node:internal/errors:371:5)
0|mm  |     at Server.listen (node:net:1405:11)
0|mm  |     at DialServer.start (/home/pi/MagicMirror/modules/MMM-Screencast/DialServer.js:123:17)
0|mm  |     at Class.socketNotificationReceived (/home/pi/MagicMirror/modules/MMM-Screencast/node_helper.js:22:21)
0|mm  |     at Socket.<anonymous> (/home/pi/MagicMirror/js/node_helper.js:109:11)
0|mm  |     at Socket.emit (node:events:394:28)
0|mm  |     at Socket.emitUntyped (/home/pi/MagicMirror/node_modules/socket.io/dist/typed-events.js:69:22)
0|mm  |     at /home/pi/MagicMirror/node_modules/socket.io/dist/socket.js:466:39
0|mm  |     at processTicksAndRejections (node:internal/process/task_queues:78:11) {
0|mm  |   code: 'ERR_SERVER_ALREADY_LISTEN'
0|mm  | }
0|mm  | [04.03.2022 13:59.15.971] [ERROR] MagicMirror will not quit, but it might be a good idea to check why this happened. M
aybe no internet connection?
0|mm  | [04.03.2022 13:59.15.973] [ERROR] If you think this really is an issue, please open an issue on GitHub: https://github
.com/MichMich/MagicMirror/issues
```

But as I said, the API and integration still works for me.

**Comment by fribse** [comment] 2022-03-06 11:50
Ok, so you have an old upgraded installation where it works, and I've tried a brand new installation where it fails.
The sandbox error is an uostream error, and doesn't mean anything.
I've seen the 'already listen' before.
I wonder if the order in the config file matter.
Where have you put the screencast module?

**Comment by sindrebroch** [comment] 2022-03-06 18:01
Not a bad idea. I have Screencast before Remote-Control, as module number 9 and 10 respectively. I tried switching them around but no difference for me.

**Comment by fribse** [comment] 2022-03-24 10:08
Hmm, no change for me when trying to reorder them, very odd. I really hate that I can't have both. You don't have an extra pi you could test on, do you?
I can't figure out why you can't reproduce it, except that maybe you are not on the latest of the code and updates.
When I test on my spare pi, with the latest raspberry pi os, and use the automated install, it fails EVERY time.

**Comment by fribse** [comment] 2022-03-30 19:48
No, one rarely has pi's just lying around :-)
Well I've done a completely simple install.
Raspberry imager, latest raspberry pi os (with desktop) both tried 32bit and 64bit.
Then using the installer from sdetweil (https://github.com/sdetweil/MagicMirror_scripts)
I also tried doing the install manually.
I then started changing the default config to include remote control and screencast.
I've tried both with modifying to fit the region, and leaving it at us.
I've tried on a RPi4 4GB, as that is a test machine I use. I also tried when cleaning up the real magic mirror using the RPi3B in that.
That's about it.

**Comment by sindrebroch** [comment] 2022-03-30 20:55
Great, will report back when I get the chance to test!

**Comment by sindrebroch** [comment] 2022-04-02 17:26
Alright, I just reinstalled, and could still not reproduce the issue. Here are my steps.

- I installed the default Rpi OS image with the Raspberry Pi Imager, set hostname, wifi and ssh in the installer.
- Used sdetweil's install-script. First time I tried this, but seems to work well.
- I then cloned MMM-Remote-Control and MMM-Screencast, and added them to config.js
- I also changed a few other things in config.js. 
```
address = "0.0.0.0"

ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1", "192.168.1.0/24", "192.168.30.0/24"]

locale: "nb-NO"
```
- I Also added my calendar, weather with apiKey, newsfeed with my own url, and custom compliments, but no other components added, only the customized the existing ones.

**Comment by fribse** [comment] 2022-04-02 18:21
Ok, so the latest image, did you update it before installing?
I guess the o ly difference is the language settings, I'll retest with that

**Comment by sindrebroch** [comment] 2022-04-03 12:54
I did not update before installing, no.

**Comment by sindrebroch** [comment] 2022-04-03 12:57
Also I'm doing this is on a Raspberry Pi 3B. 

Ran updates now, but none were available, so either the scripts run an update, or the image was updated i guess.

**Comment by fribse** [comment] 2022-05-15 08:07
I'm doing yet another try, doing JUST your steps, here's hoping :-D
Allthough I have to install it on a RPi4, it shouldn't change anything.
You wrote "default Rpi OS" so I guess that is with the GUI, I've done the same here.

**Comment by fribse** [comment] 2022-05-15 08:21
Darned, it works, what on earth is gong on?
I've change the norwegian to danish, still works, now I'll go and change some of the builtin modules one by one...

**Comment by fribse** [comment] 2022-05-15 08:39
I've gone through all the standard modules, and have modified them to my config, and everything still works.
Now it's time for the custom modules, first up is MMM-News-QR, then MMM-MyCommute and finally MMM-ModuleScheduler.

**Comment by fribse** [comment] 2022-05-15 11:00
Done, everything is back, and now it's working, really weird.
BUT with the latest RaspberryPi OS I can't get it to rotate the screen, arrrrr, starting over, but with a lot more optimism.

**Comment by sindrebroch** [comment] 2022-05-15 11:06
Great! Glad to hear it's finally working for you!

Yeah, I struggled with screen rotation the last time as well. Don't remember what finally did it, but I tried all the tricks. 

I think I'll close the issue for now then, and you can reopen or open a new one if any issues appear.

**Closed by sindrebroch** 2022-05-15 11:06 UTC
Labels: bug, not reproducible

**Comment by fribse** [comment] 2022-05-15 12:05
Could you post what your /boot/cmdline.txt looks like, I think that is where it's supposed to go (the rotation thing)

**Comment by sindrebroch** [comment] 2022-05-15 18:23
That's not a file I have touched, but here it is.

`console=serial0,115200 console=tty1 root=PARTUUID=0dc1af67-02 rootfstype=ext4 fsck.repair=yes rootwait`

**Comment by sindrebroch** [comment] 2022-05-15 18:25
I have display_rotate=1 in /boot/config.txt at least, but not sure if that was what made it work
